spring:
  datasource:
    url: jdbc:h2:mem:abidjan_dev;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Disable Flyway in dev to avoid applying Postgres-specific migrations on H2
flyway:
  enabled: false

jwt:
  secret: d1f2e3c4b5a6978877665544332211ffeeddccbbaa99887766554433221100aa
  expirationMs: 3600000

logging:
  level:
    org.springframework: INFO
